services:
  app:
    container_name: app-dev
    build: .
    ports:
      - "3000:${PORT:-3000}"
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: no

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: on-failure

  db:
    container_name: db-dev
    image: postgres:18.3-alpine
    ports: ["5432:5432"]
    restart: on-failure
    shm_size: 128mb
    env_file:
      - ./database/.env
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: